
# Experiment Setup, Logging Specifications, Environment
experiment:
  description: |
    > 0000 establish fully supervised baselines on ISIC 2017.
    > Experiment: Baseline, 1 RGB frame, 1 pos - 512x512, sgd
  id: "0000"
  name: 'dataset_arch_opt'
  project: 'bibm2020'
  debug:                                            # (Correct Alignment)
    mode: False                                     # < Check
    wandb: True                                     # < Check
    save: True                                      # < Check
    break_train_iter: False                         # < Check
    break_test_iter: False                          # < Check
    test_every_n_epochs: 1
  seed: 310

# Experiment Global Data Specifications (defines what an example is)
data:  # describing project-wide data specifications
  name: isic_2017
  isic_2017:
    classnames: ['binary']


# Training Specifications
train:
  start_epoch: 1
  epochs: 300
  
  optimizer:
    name: 'adam'  # sgd, nesterov, adam
    lr: .001
    momentum: 0 # 0.9
    wt_decay: 0 # 0.0001
    adam:
      betas: [0.9, 0.999]
    
  scheduler:
    name: 'uniform'
    rampup_rates: []
    factor: 0.1
    plateau:
      patience: 10
    step:
      steps: [0.25, 0.65]

  batch_size: -1   # <!CHANGE
  shuffle: False
  input: [-1,-1]
  transforms:  []


# Testing Specifications
test:
  batch_size: -1
  transforms: [] # resize (req for batch creation!): even dims

# Model / Criterion / Other nn.Module Specifications
model:
  name: 'unet'
  unet:
    bilinear: True
  bigunet:
    bilinear: True
  nestedunet:
    deepsup: False

criterion:
  name: 'cross_entropy'
  focal:
    alpha: 1
    gamma: 2
  softdice:
    square_denom: False
  softjiccard:
    log_loss: False
  tversky:
    alpha: 0.5
    beta: 0.5
    
  